name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  publish_image:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --tag ghcr.io/TrejoJulian/segui-tus-compras-frontend:latest
    - name: push image to githubregistry
      run: |
        echo "${{ secrets.SEGUI_TUS_COMPRAS_TOKEN }}" | docker login ghcr.io -u TrejoJulian --password-stdin
        docker push ghcr.io/TrejoJulian/segui-tus-compras-frontend:latest