name: E2E Tests

on:
    pull_request:
        branches: ["dev"]
    push:
        branches: ["dev"]

jobs:
    cypress-e2e:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout frontend
              uses: actions/checkout@v3

            - name: Set up Docker Compose
              run: |
                  docker compose -f docker/docker-compose.yml up -d --build

            - name: Wait for backend and frontend
              run: |
                  echo "Waiting for services to be up..."
                  until curl -s http://localhost:8000 > /dev/null; do echo "Waiting for backend..."; sleep 5; done
                  until curl -s http://localhost:5173 > /dev/null; do echo "Waiting for frontend..."; sleep 5; done

            - name: Run Seeder for test user
              run: docker exec laravel_app php artisan db:seed --class=UsersSeeder

            - name: Install Node.js and Cypress deps
              uses: actions/setup-node@v3
              with:
                  node-version: 18

            - run: npm ci
            - run: npx cypress install

            - name: Run Cypress tests
              run: npm run test:e2e

            - name: Shutdown Docker
              if: always()
              run: docker compose -f docker/docker-compose.ci.yml down
